### ISSUE TITLE
Custom labels?

### ISSUE THREAD

**Issue by 5chdn** [Muhnad/dont-merge#6]
Hi @Muhnad - is it possible to specify custom labels that should prevent merging?

**Comment by Muhnad** [comment]
Hi @5chdn, at this time it's not available to add a custom label, you can open PR for this feature, but for now, you can add your custom label by doing these steps:
- Fork repo
- Edit this file https://github.com/Muhnad/dont-merge/blob/master/src/utils.js
- use it :smile:

**Comment by 5chdn** [comment]
Ahhhh `do( no|n')t` ... I was grep'ing around and couldn't find it obviously :D

**Comment by Muhnad** [comment]
#7
